<?php

// @codingStandardsIgnoreFile

/** @var \Unbxd\ProductFeed\Block\Adminhtml\System\Config\Fieldset\Catalog $block */
?>
<div class="unbxd-system-config-information-container module-info">
    <div class="block header">
        <h2>
            <strong><?= /* @escapeNotVerified */ __('Product Feed v. %1', $block->getModuleVersion()) ?></strong>&nbsp;
            <span><?= /* @escapeNotVerified */ __('by') ?></span>
        </h2>
        <a class="logo" href="<?= /* @escapeNotVerified */ $block->getUnbxdReferenceUrl()?>" target="_blank">
            <img src="<?php echo $block->getLogoSrc() ?>" alt="<?= /* @escapeNotVerified */ __('Unbxd') ?>" />
        </a>
    </div>
    <div class="block content">
        <p><?= /* @escapeNotVerified */ __('Have a question? Please refer to the <a href="%1">documentation</a>.',
                $block->getUnbxdReferenceUrl('feed_doc')) ?></p>
    </div>
</div>
<div class="unbxd-system-config-information-container catalog">
    <div class="block notification">
        <?php
        $isSynchronizationAttempt = $block->isSynchronizationAttempt();
        $stateClassName = $block->getIsComplete() ? 'success' : 'warning';
        $message = $block->getMessageByStatus();
        ?>
        <div class="messages-container">
            <div class="messages">
                <div class="message message-<?php echo $stateClassName ?>">
                    <span><?= /* @escapeNotVerified */ $message ?></span>
                    <?php if ($isSynchronizationAttempt): ?>
                        <a class="link" href="<?= /* @escapeNotVerified */ $this->getUrl('unbxd_productfeed/feed/view')?>">
                            <?= /* @escapeNotVerified */ __('View details') ?>
                        </a>
                    <?php endif; ?>
                </div>
            </div>
        </div>
    </div>
    <?php if ($isSynchronizationAttempt): ?>
        <div class="block content additional-information"
             data-mage-init='{"collapsible":{
                "animate":{
                    "duration":800,
                    "easing":"easeOutCubic"
                },
                "openedState":"active",
                "active":false
                }}' >
            <p class="title" data-role="title"><?= /* @escapeNotVerified */ __('Last synchronization information:') ?></p>
            <div data-role="content">
                <table>
                    <tbody>
                    <?php if ($type = $block->getLastSynchronizationOperationType()): ?>
                        <tr>
                            <th><?= /* @escapeNotVerified */ __('Synchronization Type') ?></th>
                            <td><?= /* @escapeNotVerified */ __($type) ?></td>
                        </tr>
                    <?php endif; ?>
                    <?php if ($dateTime = $block->getLastCatalogSyncDatetime()): ?>
                        <tr>
                            <th><?= /* @escapeNotVerified */ __('Datetime') ?></th>
                            <td><?= /* @escapeNotVerified */ __($dateTime) ?></td>
                        </tr>
                    <?php endif; ?>
                    <?php if ($status = $block->getLastSynchronizationStatusHtml()): ?>
                        <tr>
                            <th><?= /* @escapeNotVerified */ __('Status') ?></th>
                            <td><?= /* @escapeNotVerified */ __($status) ?></td>
                        </tr>
                    <?php endif; ?>
                    <?php if ($block->isUploadedFeedDetailsEnabled()): ?>
                        <?php if ($uploadId = $block->getLastUploadId()): ?>
                            <tr>
                                <th><?= /* @escapeNotVerified */ __('Upload ID') ?></th>
                                <td><?= /* @escapeNotVerified */ __($uploadId) ?></td>
                            </tr>
                        <?php endif; ?>
                        <?php if ($uploadedSize = $block->getUploadedSize()): ?>
                            <tr>
                                <th><?= /* @escapeNotVerified */ __('Total Uploaded Size') ?></th>
                                <td><?= /* @escapeNotVerified */ __(
                                        sprintf('%s (children products are not counted)', $uploadedSize)
                                    ) ?>
                                </td>
                            </tr>
                        <?php endif; ?>
                    <?php endif; ?>
                    </tbody>
                </table>
            </div>
        </div>
    <?php endif; ?>
    <div class="block content"
         data-mage-init='{"collapsible":{
            "animate":{
                "duration":800,
                "easing":"easeOutCubic"
            },
            "openedState":"active",
            "active":false
            }}'>
        <p class="title" data-role="title"><?= /* @escapeNotVerified */ __('Manual product catalog synchronization:') ?></p>
        <div data-role="content">
            <ul>
                <li><a href="#unbxd_catalog_actions-head">
                        <?= /* @escapeNotVerified */ __('by actions below (see Manual Synchronization section)') ?></a>
                </li>
                <li><?= /* @escapeNotVerified */ __('by available CLI commands: %1',
                        '<br/><code>php bin/magento unbxd:product-feed:full</code><br/>
                    <code>php bin/magento unbxd:product-feed:incremental</code>') ?></li>
            </ul>
            <a class="link external" target="_blank" href="<?= /* @escapeNotVerified */ $block->getCommandLineReferenceUrl() ?>">
                <span><?= /* @escapeNotVerified */ __('Get started with command-line') ?></span>
            </a>
        </div>
    </div>
</div>