<?php

// @codingStandardsIgnoreFile

/** @var \Unbxd\ProductFeed\Block\Adminhtml\System\Config\Fieldset\Setup $block */
?>
<div class="unbxd-system-config-information-container setup">
    <div class="block header">
        <a class="logo" href="<?= /* @escapeNotVerified */ $block->getUnbxdReferenceUrl()?>" target="_blank">
            <img src="<?php echo $block->getLogoSrc() ?>" alt="<?= /* @escapeNotVerified */ __('Unbxd') ?>" />
        </a>
    </div>
    <div class="block content">
        <p><?= /* @escapeNotVerified */ __('How it works? Please refer to the <a href="%1">documentation</a>.',
                $block->getUnbxdReferenceUrl('intro')) ?></p>
    </div>
</div>